### ISSUE TITLE
Loading pretrained model weights from data/pretrain_model/Resnet50.npy，I met this problem

### ISSUE THREAD

**Issue by chl916185** [xmyqsh/FPN#11]
num gt: 2
num fg: 17
num bg: 111
cudaCheckError() failed in ROIPoolForward: invalid device function
cudaCheckError() failed in ROIPoolForward: driver shutting down
2017-08-21 10:19:34.578317: F tensorflow/stream_executor/cuda/cuda_driver.cc:312] Check failed: CUDA_SUCCESS == cuCtxSetCurrent(cuda_context->context()) (0 vs. 4)
2017-08-21 10:19:34.578347: E tensorflow/stream_executor/stream.cc:289] Error recording event in stream: error recording CUDA event on stream 0x61a7d80: CUDA_ERROR_DEINITIALIZED; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
2017-08-21 10:19:34.578429: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_DEINITIALIZED
2017-08-21 10:19:34.578450: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
Command terminated by signal 6
65.76user 10.62system 1:13.23elapsed 104%CPU (0avgtext+0avgdata 1891988maxresident)k
0inputs+3016outputs (0major+831469minor)pagefaults 0swaps
@xmyqsh ，I met this problem, how to solve？

**Comment by xmyqsh** [comment]
@chl916185 
Are you training FPN end-to-end?
I haven't encountered problems like this under end-to-end training.
While I have encountered problems like this under alt-opt training when I set gpu=1.
And if I set gpu=0, this problem disappeared.
[#8517](https://github.com/tensorflow/tensorflow/issues/8517) is also discussing this problem.

**Comment by chl916185** [comment]
python ./faster_rcnn/test_net.py --gpu 3 --weights
output/FPN_end2end/voc_2007_trainval/FPN_iter_200.ckpt --imdb voc_2007_test --cfg ./experiments/cfgs/FPN_end2end.yml --network FPN_test

**Comment by chl916185** [comment]
Which version is your tensorflow？
@xmyqsh

**Comment by xmyqsh** [comment]
@chl916185 
1.1.0-rc0
For these problems, set gpu=0 will be OK.

**Comment by luuuyi** [comment]
@chl916185 can you share your solution for this problem?
cudaCheckError() failed in ROIPoolForward: invalid device function
